#!/usr/bin/env node
const fs = require('fs');

// Remap calls to typescript's createProgram with vue-tsc's proxy

const readFileSync = fs.readFileSync;
const tscPath = require.resolve('typescript/lib/tsc');
const proxyPath = require.resolve('vue-tsc/out/index');

fs.readFileSync = (...args) => {
    if (args[0] === tscPath) {
        let tsc = readFileSync(...args);

        // add *.vue files to allow extensions
        tryReplace(/supportedTSExtensions = .*(?=;)/, s => s + '.concat([[".vue"]])');
        tryReplace(/supportedJSExtensions = .*(?=;)/, s => s + '.concat([[".vue"]])');
        tryReplace(/allSupportedExtensions = .*(?=;)/, s => s + '.concat([[".vue"]])');

        // proxy createProgram apis
        tryReplace(/function createProgram\(.+\) {/, s => s + ` return require(${JSON.stringify(proxyApiPath)}).createProgram(...arguments);`);

        return tsc;

        function tryReplace(search, replace) {
            const before = tsc;
            tsc = tsc.replace(search, replace);
            const after = tsc;
            if (after === before) {
                throw 'Search string not found: ' + JSON.stringify(search.toString());
            }
        }
    }
    return readFileSync(...args);
};

const TypeDoc = require(require.resolve('typedoc'));

// Run typedoc, using modified version of the their bin:
// https://github.com/TypeStrong/typedoc/blob/master/bin/typedoc

const ExitCodes = {
    Ok: 0,
    OptionError: 1,
    NoEntryPoints: 2,
    CompileError: 3,
    ValidationError: 4,
    OutputError: 5,
    ExceptionThrown: 6,
};

const app = new TypeDoc.Application();

app.options.addReader(new TypeDoc.ArgumentsReader(0));
app.options.addReader(new TypeDoc.TypeDocReader());
app.options.addReader(new TypeDoc.TSConfigReader());
app.options.addReader(new TypeDoc.ArgumentsReader(300));

app.bootstrap();

run(app)
    .catch((error) => {
        console.error("TypeDoc exiting with unexpected error:");
        console.error(error);
        return ExitCodes.ExceptionThrown;
    })
    .then((exitCode) => (process.exitCode = exitCode));

async function run(app) {
    if (app.options.getValue("version")) {
        console.log(app.toString());
        return ExitCodes.Ok;
    }

    if (app.options.getValue("help")) {
        console.log("Please try `typedoc help` for options help");
        return ExitCodes.Ok;
    }

    if (app.options.getValue("showConfig")) {
        console.log(app.options.getRawValues());
        return ExitCodes.Ok;
    }

    if (app.logger.hasErrors()) {
        return ExitCodes.OptionError;
    }
    if (
        app.options.getValue("treatWarningsAsErrors") &&
        app.logger.hasWarnings()
    ) {
        return ExitCodes.OptionError;
    }

    if (app.options.getValue("entryPoints").length === 0) {
        app.logger.error("No entry points provided");
        return ExitCodes.NoEntryPoints;
    }

    if (app.options.getValue("watch")) {
        app.convertAndWatch(async (project) => {
            const out = app.options.getValue("out");
            if (out) {
                await app.generateDocs(project, out);
            }
            const json = app.options.getValue("json");
            if (json) {
                await app.generateJson(project, json);
            }

            if (!out && !json) {
                await app.generateDocs(project, "./docs");
            }
        });
        return ExitCodes.Ok;
    }

    const project = app.convert();
    if (!project) {
        return ExitCodes.CompileError;
    }
    if (
        app.options.getValue("treatWarningsAsErrors") &&
        app.logger.hasWarnings()
    ) {
        return ExitCodes.CompileError;
    }

    app.validate(project);
    if (app.logger.hasErrors()) {
        return ExitCodes.ValidationError;
    }
    if (
        app.options.getValue("treatWarningsAsErrors") &&
        app.logger.hasWarnings()
    ) {
        return ExitCodes.ValidationError;
    }

    if (app.options.getValue("emit") !== "none") {
        const out = app.options.getValue("out");
        if (out) {
            await app.generateDocs(project, out);
        }
        const json = app.options.getValue("json");
        if (json) {
            await app.generateJson(project, json);
        }

        if (!out && !json) {
            await app.generateDocs(project, "./docs");
        }

        if (app.logger.hasErrors()) {
            return ExitCodes.OutputError;
        }
        if (
            app.options.getValue("treatWarningsAsErrors") &&
            app.logger.hasWarnings()
        ) {
            return ExitCodes.OutputError;
        }
    }

    return ExitCodes.Ok;
}
